### ISSUE TITLE
Spoon can't read screenshots from L preview

### ISSUE THREAD

**Issue by yogurtearl** [square/spoon#189] opened 2014-06-30 19:42 UTC
This doesn't work on, on L preview:
```
adb pull /data/data/<package_name>/app_spoon-screenshots
```

Even though I can do this:
```
adb shell ls /data/data/<package_name>/app_spoon-screenshots
```

It may get fixed in L at some point ( I filed a bug here: https://code.google.com/p/android/issues/detail?id=72823 ), but it would be nice to have a Spoon work around in the mean time. maybe save the screenshots to a different location?

**Comment by lbielski** [comment] 2015-01-13 16:55
This is how Robotium does it:

This is on the phone:
    public String screenshotSavePath = Environment.getExternalStorageDirectory() + "/Robotium-Screenshots/"

When you execute `echo $SECONDARY_STORAGE` or `echo $EXTERNAL_STORAGE` in adb one of them will give you the path to where 'Robotium-Screenshots' is located.

Spoon could essentially do the same. `sdcard` doesn't have to be hardcoded anywhere.
I can confirm that this approach works for all phones (at least on 180 devices we have, Lollipop included).

**Comment by rtruxler** [comment] 2015-01-28 22:24
@edenman any updates or known workaround in the meantime?

**Comment by edenman** [comment] 2015-01-28 22:32
@rtruxler Unfortunately, no.

**Comment by joe-engel** [comment] 2015-02-05 20:21
Hi, I made a fork to address this issue.
https://github.com/joe-engel/spoon

Spoon uses getExternalStorageDirectory() to save screenshots. SpoonDeviceRunner then calls "echo $EXTERNAL_STORAGE" in the ADB shell to get the correct folder path for the screenshots.

I tested it on three devices: Nexus 5 running Lollipop, LG-E980 running 4.1.2, and Galaxy S3 running 4.1.2.

This is my first pull request on GitHub, so any feedback is appreciated.

**Comment by mathias21** [comment] 2015-02-05 22:55
Hi all

I think I fixed the issue. I need to generalize the screenshots path (not hardcoded) and do all the modifications to pass the checkstyle plugin check.
@edenman would it be ok to make a pull request? :)

**Comment by mathias21** [comment] 2015-02-05 22:59
Hi @joe-engel 

I was closer to this solution, I just needed to get the executeShellCommand call running ^_^
The problem was Lollipop is not using /data/data folder for app storage, so when you try to access that path, hardcoded inside SpoonDeviceRunner, Permission denied error was shown.
I will test it tomorrow. But it looks promising. 

Thank you for this contribution.

**Comment by joe-engel** [comment] 2015-02-05 23:06
@mathias21, that's cool. Thanks for working on it and thanks for your offer to test it some more.

**Comment by mathias21** [comment] 2015-02-05 23:11
@joe-engel could you manage to skip the checkstyle plugin? I had to deactivate it to debug the solution, it was complaining when Eclipse formatted all the code... -_-

I will let you know tomorrow if that is working for me as well. :+1:

**Comment by joe-engel** [comment] 2015-02-06 01:41
@mathias21 I'm using intellij and I was actually wanting for some local checkstyle action. I checked in a bunch of stuff that failed style validation. Planning on investigating that next time.

**Comment by edenman** [comment] 2015-02-06 03:58
Generally, the `SquareAndroid` profile in https://github.com/square/java-code-styles should pass all our checkstyle rules.

**Comment by joe-engel** [comment] 2015-02-06 04:00
Thanks Eric :)

**Comment by mathias21** [comment] 2015-02-06 08:37
Hi @joe-engel 

After trying to compile your fix in my Eclipse, with Maven install, it is dropping two checkstyle errors.
[folder]/SpoonFixed/spoon-client/src/main/java/com/squareup/spoon/Spoon.java:10: Using * import must be avoided - java.io.*.
[folder]/SpoonFixed/spoon-client/src/main/java/com/squareup/spoon/Spoon.java:107:66: ',' not followed by blank space

I had to translate it because my computer is in Spanish. I will try in my branch.

**Comment by mathias21** [comment] 2015-02-06 10:45
Hi all

I have fixed the issue, also with checkstyle passed. I will make a brach and I will make a pull request.

Thanks to @joe-engel to show me how to get the externalStorageDir inside SpoonDevideRunner class, that was my last point to fix this.

**Comment by joe-engel** [comment] 2015-02-06 15:53
@mathias21 I think if you were getting checkstyle errors in my fork you were probably looking at the wrong branch. The working branch for this issue is screenshots-for-lollipop. This branch is passing checkstyle and has been reviewed by Jake and Eric here: https://github.com/square/spoon/pull/227

Sorry, I should have clarified the branch when you offered to test yesterday. And I also should have left master clean so it's obvious that's not the right one.

Note my version contains an additional update for kitkat/lollipop: It increases the size of the screenshots to capture content which may be behind transparent system bars or navigation. (Check the first two lines of takeScreenshot)

**Comment by mathias21** [comment] 2015-02-06 16:11
Hi @joe-engel 

Ok, it looks like you are ahead on this. Not more time today to keep on working on this, so I will have a look on Monday.

Good weekend.

**Comment by joe-engel** [comment] 2015-02-06 16:31
Thanks mate, you too :)

**Comment by edenman** [comment] 2015-03-16 23:08
This is done: screenshots work again in 1.1.3.  Thanks all!

**Closed by edenman** 2015-03-16 23:08 UTC
