### ISSUE TITLE
App apk installation failed : INSTALL_FAILED_VERSION_DOWNGRADE

### ISSUE THREAD

**Issue by senth30** [square/spoon#448] opened 2017-04-06 02:56 UTC
App apk installation failed with the below error,

2017-04-03 23:07:24 [SR.runTests] Executing instrumentation suite on 1 device(s).
2017-04-03 23:08:28 [SDR.run] [10.63.255.46:5555] app apk install failed.  Error [INSTALL_FAILED_VERSION_DOWNGRADE]

Looks like there was a later version of the app was installed on the device. I'm looking to force the downgrade like "adb install -r -d app.apk" equivalent in spoon runner. Is this something already supported in spoon runner?

**Comment by JakeWharton** [comment] 2017-04-25 22:53
Dupe of https://github.com/square/spoon/issues/295

**Closed by JakeWharton** 2017-04-25 22:53 UTC
