### ISSUE TITLE
Screenshots are not pulled from some devices

### ISSUE THREAD

**Issue by acortelyou** [square/spoon#166] opened 2014-01-14 19:29 UTC
I'm running spoon against a USB hub with eight real devices, with partial great success.

Six of them work great: 
The tests are run, screenshots are taken, pulled and processed.

On the other two devices:
The tests run, screenshots are taken but are not pulled by the runner.

Using spoon-runner directly with ```--debug``` enabled results in no logged errors.

Watching logcat when the pull should occur didn't show anything unexpected except for a ```D/jdwp: adbd disconnected```, but I'm fairly sure thats unrelated.

Using the ADB shell I can see the screenshots on the path spoon logged that it would be pulling from.

```adb pull /data/data/com.example.app/app_spoon-screenshots``` retrieves the screenshots with no problems.

The source for spoon-runner seems to indicate that it's pulling using a similar method via ddmlib.

I tried widening the permissions for the /data/data/com.example.app/app_spoon-screenshots folder to 777 but got no change in result.

The two misbehaving devices are running Android 2.3.5/6 and were both manufactured by HTC.

This may resolve itself when Issue #4 is closed

**Comment by edenman** [comment] 2015-03-16 23:14
Closing this out, not planning on spending any time on weird HTC-specific gingerbread bugs.  PRs welcome if you still care and figure out what the issue is!

**Closed by edenman** 2015-03-16 23:14 UTC
