### ISSUE TITLE
Thumbnails not shown in resulting HTML with Marshmallow

### ISSUE THREAD

**Issue by pvegh** [square/spoon#293] opened 2015-10-21 14:16 UTC
The following snippet is missing in the HTML for devices that are running API 23.

```
<ul class="thumbnails">
   <li class="span2">
      <a href="../image/emulator-5554/com.my.package/testStartup/1445434855746_startup.png" class="thumbnail">
         <img src="../image/emulator-5554/com.my.package.MainActivityTests/testStartup/1445434855746_startup.png" title="Startup">
      </a>
   </li>
</ul>
```

The result is the same on an emulator and a device both running Marshmallow.
The thumbnails are shown for the Lollipop emulator I tried.

Looking into the pulled data, I can see some difference in the folder structure under *images*.

For *Lollipop*:
DEVICE_SERIAL/APP_PACKAGE/TEST_NAME/*.png

For *Marshmallow*:
DEVICE_SERIAL/com.squareup.spoon.Spoon/screenshot/*.png (all .PNGs in there)

Does it make any sense? Can I provide any more input?

**Comment by edenman** [comment] 2015-10-21 17:39
@pvegh hrm.  we parse that package name from the instrumentation app's `AndroidManifest.xml` (the `targetPackage` attribute on either the `instrumentation` or `manifest` tags).  Can you post the contents of your AndroidManifest.xml for the instrumentation app?

**Comment by JanKokalj** [comment] 2015-10-25 05:59
I have the same problem. In my case I have a helper class with defined tests (so I can call them from test classes with different localisations).

on device with api lvl <23 I get file structure:
DEVICE_SERIAL/FULLY_QUALIFIED_TEST_CLASS_NAME/METHOD_NAME/*.png

but on device with api lvl >=23, I get:
DEVICE_SERIAL/FULLY_QUALIFIED_HELPER_CLASS_NAME/HELPER_METHOD_NAME/*.png
and a console message:
[SDR.handleImages] Unable to find test for com.test.espresso.EspressoHelper#simpleActivityAndDialogLandscapeTest

This actually makes sense, since I use different class and method to take screenshots but it was confusing that it works differently than on <23.
I fixed it with providing my own class and method names to Spoon.screenshot method.

**Comment by pvegh** [comment] 2015-10-26 09:23
@edenman this is the relevant part of the Manifest:

<manifest
    xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.some.thing">

And the resulting folder is "com.some.thing.MainActivityTests" on <23.
On 23 it is "com.squareup.spoon.Spoon"

And yes I do see this message in the console too: 
Unable to find test for com.squareup.spoon.Spoon#screenshot

Is it working for you guys on API23 correctly?

**Comment by edenman** [comment] 2015-11-03 02:26
@pvegh we don't have anybody actively using Spoon at Square anymore, unfortunately.  The code in question is in SpoonInstrumentationInfo.parseFromFile if you want to take a look at fixing it:
```
          boolean isManifest = "manifest".equals(parserName);
          boolean isInstrumentation = "instrumentation".equals(parserName);
          if (isManifest || isInstrumentation) {
            for (int i = 0; i < parser.getAttributeCount(); i++) {
              String parserAttributeName = parser.getAttributeName(i);
              if (isManifest && "package".equals(parserAttributeName)) {
                testPackage = parser.getAttributeValueString(i);
              } else if (isInstrumentation && "targetPackage".equals(parserAttributeName)) {
                appPackage = parser.getAttributeValueString(i);
              } else if (isInstrumentation && "name".equals(parserAttributeName)) {
                testRunnerClass = parser.getAttributeValueString(i);
              }
            }
          }
```

I'm guessing there's a `com.squareup.spoon.Spoon` in the manifest somewhere unexpected on 23.

**Comment by pvegh** [comment] 2015-11-04 08:00
Thanks for the info.
Might I ask why you are not using it anymore? Or what you are doing instead?
Some of us always like to read about such things from Square, even a new blog entry about this would be nice (Jake & co.?)

**Comment by JakeWharton** [comment] 2015-11-04 08:18
The needs of our instrumentation testing far outgrew what Spoon is capable
of.

**Comment by pivotal-vladimir** [comment] 2015-12-14 20:42
The issue is actually in the spoon client.

It looks like that Android has a different version of java.lang.reflect.Method class that was changed in the API 23 and ```invoke()``` method doesn't have an overload there any longer and goes straight into the native invocation.

That being said ```Spoon#findTestClassTraceElement()``` returns trace element that is next to the test method (offset is hardcoded to be 3 in all cases).

I can think of two solutions:

1. Check for the api version of the device and then set the offset depending on the current API level.

2. Return the next trace element right after the first native method call once the junit/cucumber method is found.

I am leaning towards number 2. I can't really think of a case when it will produce an invalid test class.

I will submit a PR with the fix, unless someone has a better solution.

**Comment by edenman** [comment] 2016-01-07 19:31
Pretty sure this is fixed in the latest release.

**Closed by edenman** 2016-01-07 19:31 UTC

**Comment by pvegh** [comment] 2016-01-11 09:29
Thanks for the fix to all involved!
