### ISSUE TITLE
Problem with parsing logcat output

### ISSUE THREAD

**Issue by outlying** [square/spoon#302] opened 2015-11-17 15:23 UTC
My command is (1.2.1 version):

    java -jar /opt/spoon/spoon-runner.jar --apk app/build/outputs/apk/app-debug-unaligned.apk --test-apk app/build/outputs/apk/app-debug-androidTest-unaligned.apk --output app/build/outputs/spoon-runner/ --sdk /opt/android-sdk/

but result is somehow suprpsing:

    2015-11-17 16:06:20 [SR.runTests] Executing instrumentation suite on 1 device(s).
    Exception in thread "Thread-1" java.lang.IllegalStateException: No logcat header processed yet, failed to parse line: --------- beginning of system
    	at com.android.ddmlib.logcat.LogCatMessageParser.processLogLines(LogCatMessageParser.java:123)
    	at com.android.ddmlib.logcat.LogCatReceiverTask$LogCatOutputReceiver.processLogLines(LogCatReceiverTask.java:112)
    	at com.android.ddmlib.logcat.LogCatReceiverTask$LogCatOutputReceiver.processNewLines(LogCatReceiverTask.java:107)
    	at com.android.ddmlib.MultiLineReceiver.addOutput(MultiLineReceiver.java:100)
    	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:519)
    	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:382)
    	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:353)
    	at com.android.ddmlib.Device.executeShellCommand(Device.java:604)
    	at com.android.ddmlib.logcat.LogCatReceiverTask.run(LogCatReceiverTask.java:75)
    	at java.lang.Thread.run(Thread.java:745)
    2015-11-17 16:06:53 [SDR.handleFiles] Found class name dirs: [Ljava.io.File;@58ceff1

so far I have no idea what's wrong with it

**Comment by edenman** [comment] 2015-11-17 23:27
Hrm, might be an issue with the new ddmlib.  Can you see if it works on 1.2.0?

**Comment by edenman** [comment] 2015-11-17 23:29
Yeah, looks like an issue with #301.  @x2on @ligi did you guys figure out a workaround for this?  I saw you posted it on stackoverflow: http://stackoverflow.com/questions/33763128/illegalstateexception-no-logcat-header-processed-yet

**Comment by outlying** [comment] 2015-11-18 09:21
It seems that you need to update your Android SDK, usually I'm working with headless CI and I need to do my updates via cli, process is somehow automatic (simple scripts) but in this case something was missing.

But right now my builds are good, so I would suggest to future readers check your SDK very carefully. Some kind of validation from Spoon runner would be great i.e. "install this and that information"

**Comment by ligi** [comment] 2015-11-18 12:45
I am getting the error with the latest android SDK

**Comment by x2on** [comment] 2015-11-18 12:52
What version do you use?

**Comment by ligi** [comment] 2015-11-18 12:55
24.4.1

**Comment by cmc5788** [comment] 2015-11-28 04:45
Having this error, too - SDK is 23, tools are latest, having it both locally and on CI with an update script. Gradle plugin is 1.5.0. Downgrading to 1.2.0 jar fixes it.

**Comment by x2on** [comment] 2015-12-01 12:42
Hm i have the same problem now - i will dig into it...

**Comment by x2on** [comment] 2015-12-01 12:44
Output: 
```bash
2015-12-01 13:40:30 [SR.runTests] Executing instrumentation suite on 1 device(s).
Exception in thread "Thread-46" java.lang.IllegalStateException: No logcat header processed yet, failed to parse line: --------- beginning of /dev/log/main
	at com.android.ddmlib.logcat.LogCatMessageParser.processLogLines(LogCatMessageParser.java:123)
	at com.android.ddmlib.logcat.LogCatReceiverTask$LogCatOutputReceiver.processLogLines(LogCatReceiverTask.java:112)
	at com.android.ddmlib.logcat.LogCatReceiverTask$LogCatOutputReceiver.processNewLines(LogCatReceiverTask.java:107)
	at com.android.ddmlib.MultiLineReceiver.addOutput(MultiLineReceiver.java:100)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:519)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:382)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:353)
	at com.android.ddmlib.Device.executeShellCommand(Device.java:604)
	at com.android.ddmlib.logcat.LogCatReceiverTask.run(LogCatReceiverTask.java:75)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by x2on** [comment] 2015-12-01 15:01
I created a bug on android: https://code.google.com/p/android/issues/detail?id=195998
because i think the problem is in the ddmlib.

**Comment by x2on** [comment] 2015-12-02 08:11
@edenman could you please reopen the issue?

**Comment by x2on** [comment] 2015-12-03 14:42
For gradle plugin 1.5.0 you could use this workaround in your build.gradle:
```groovy
// Workaround for Multidex bug in gradle-android-plugin
// Replace Multidex dependency with some dummy dependency to avoid dex problems
// @see https://code.google.com/p/android/issues/detail?id=194609
project.getConfigurations().all { config ->
    if (config.name.contains("AndroidTest")) {
        config.resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            if (details.requested.name == "multidex") {
                details.useTarget("de.felixschulze.teamcity:teamcity-status-message-helper:1.2")
            }
        }
    }
}
```

**Comment by bootstraponline** [comment] 2016-01-18 19:12
I'm seeing the same issue using spoon 1.3.1 (latest release). Even with the work around, I still see:

```
Exception in thread "Thread-1023" java.lang.IllegalStateException: No logcat header processed yet, failed to parse line: --------- beginning of system
	at com.android.ddmlib.logcat.LogCatMessageParser.processLogLines(LogCatMessageParser.java:123)
	at com.android.ddmlib.logcat.LogCatReceiverTask$LogCatOutputReceiver.processLogLines(LogCatReceiverTask.java:112)
	at com.android.ddmlib.logcat.LogCatReceiverTask$LogCatOutputReceiver.processNewLines(LogCatReceiverTask.java:107)
	at com.android.ddmlib.MultiLineReceiver.addOutput(MultiLineReceiver.java:100)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:519)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:382)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:353)
	at com.android.ddmlib.Device.executeShellCommand(Device.java:604)
	at com.android.ddmlib.logcat.LogCatReceiverTask.run(LogCatReceiverTask.java:75)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by swissonid** [comment] 2016-01-21 15:25
Same problem here

**Comment by radnotiz** [comment] 2016-01-28 13:57
Funnily enough it seems to appear on the CI output as well: https://travis-ci.org/stanfy/spoon-gradle-plugin/builds/101013857

**Comment by ketaki03** [comment] 2016-02-02 19:08
I am also getting same error.

**Comment by weetmac** [comment] 2016-02-04 08:40
Same problem here?Is it fixed?

**Comment by RomainPiel** [comment] 2016-02-04 10:29
I don't think the fix will come from spoon so there's no need asking the question here. The issue appears to be in `ddmlib` which is coming with the gradle android plugin. A fix seems to be on its way, see https://code.google.com/p/android/issues/detail?id=195998 but we won't be able to confirm until a new version of the gradle android plugin is released.

**Comment by weetmac** [comment] 2016-02-04 11:12
The 1.2.0 version can work properly

**Comment by riwnodennyk** [comment] 2016-02-26 12:41
Seems to be fixed with `com.android.tools.build:gradle:2.0.0-beta6`

**Comment by RomainPiel** [comment] 2016-02-26 14:56
`com.android.tools.build:gradle:2.0.0-beta6` didn't change anything for me, weird

**Comment by bagintz** [comment] 2016-03-10 19:07
Is the only fix to revert to 1.2?  Where can I find the runner Jar with dependencies for that?  What will I miss out on with that version?

**Comment by bagintz** [comment] 2016-03-11 01:11
Thanks! @coolmaxter

**Comment by nekdenis** [comment] 2016-03-18 12:24
Still no better solutions than revert to 1.2? Got the same in my jenkins

**Comment by ObjectiveTruth** [comment] 2016-04-02 14:04
@riwnodennyk's fix worked for me. Still outputs the crash but exits with `code 0` and output is as expected which is good enough for me :+1: 

Here's the output from `CircleCI`

```
016-04-02 10:00:20 [SR.runTests] Executing instrumentation suite on 1 device(s).
Exception in thread "Thread-1" java.lang.IllegalStateException: No logcat header processed yet, failed to parse line: --------- beginning of crash
        at com.android.ddmlib.logcat.LogCatMessageParser.processLogLines(LogCatMessageParser.java:123)
        at com.android.ddmlib.logcat.LogCatReceiverTask$LogCatOutputReceiver.processLogLines(LogCatReceiverTask.java:112)
        at com.android.ddmlib.logcat.LogCatReceiverTask$LogCatOutputReceiver.processNewLines(LogCatReceiverTask.java:107)
        at com.android.ddmlib.MultiLineReceiver.addOutput(MultiLineReceiver.java:100)
        at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:519)
        at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:382)
        at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:353)
        at com.android.ddmlib.Device.executeShellCommand(Device.java:604)
        at com.android.ddmlib.logcat.LogCatReceiverTask.run(LogCatReceiverTask.java:75)
        at java.lang.Thread.run(Thread.java:745)
2016-04-02 10:01:06 [SDR.handleFiles] Found class name dirs: [Ljava.io.File;@3fb6a447
```

**Comment by roman-mazur** [comment] 2016-04-28 06:06
For those who are using https://github.com/stanfy/spoon-gradle-plugin, the problem is fixed if you use Android gradle plugin 2.0.0.

**Comment by edenman** [comment] 2016-04-28 16:27
Thanks @roman-mazur!

**Closed by edenman** 2016-04-28 16:27 UTC
Labels: bug

**Comment by wunspe** [comment] 2016-04-29 09:52
I still ger error  with using https://github.com/stanfy/spoon-gradle-plugin and android gradle  plugin 2.0.0.
<code>
016-04-29 12:43:58 [SDR.printStream] [bfbdda2b] STDERR Exception in thread "Thread-1" java.lang.IllegalStateException: No logcat header processed yet, failed to parse line: --------- beginning of main
09:43:58 2016-04-29 12:43:58 [SDR.printStream] [bfbdda2b] STDERR 	at com.android.ddmlib.logcat.LogCatMessageParser.processLogLines(LogCatMessageParser.java:123)
09:43:58 2016-04-29 12:43:58 [SDR.printStream] [bfbdda2b] STDERR 	at com.android.ddmlib.logcat.LogCatReceiverTask$LogCatOutputReceiver.processLogLines(LogCatReceiverTask.java:112)
09:43:58 2016-04-29 12:43:58 [SDR.printStream] [bfbdda2b] STDERR 	at com.android.ddmlib.logcat.LogCatReceiverTask$LogCatOutputReceiver.processNewLines(LogCatReceiverTask.java:107)
09:43:58 2016-04-29 12:43:58 [SDR.printStream] [bfbdda2b] STDERR 	at com.android.ddmlib.MultiLineReceiver.addOutput(MultiLineReceiver.java:100)
09:43:58 2016-04-29 12:43:58 [SDR.printStream] [bfbdda2b] STDERR 	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:519)
09:43:58 2016-04-29 12:43:58 [SDR.printStream] [bfbdda2b] STDERR 	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:382)
09:43:58 2016-04-29 12:43:58 [SDR.printStream] [bfbdda2b] STDERR 	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:353)
09:43:58 2016-04-29 12:43:58 [SDR.printStream] [bfbdda2b] STDERR 	at com.android.ddmlib.Device.executeShellCommand(Device.java:604)
09:43:58 2016-04-29 12:43:58 [SDR.printStream] [bfbdda2b] STDERR 	at com.android.ddmlib.logcat.LogCatReceiverTask.run(LogCatReceiverTask.java:75)
09:43:58 2016-04-29 12:43:58 [SDR.printStream] [bfbdda2b] STDERR 	at java.lang.Thread.run(Thread.java:745)
09:43:58 2016-04-29 12:43:58 [SDR.runInNewProcess] Process.waitFor() finished for [bfbdda2b] with exitCode 0
</code>

**Comment by roman-mazur** [comment] 2016-04-29 10:32
Not sure how to help you. It might depend on a combination of device SDK version and DDMS version used by the plugins.
With travis builds of the spoon gradle, we had this problem with Lollipop emulator.
https://travis-ci.org/stanfy/spoon-gradle-plugin/builds/126034640
But it was gone after Android gradle plugin update:
https://travis-ci.org/stanfy/spoon-gradle-plugin/builds/126036087

**Comment by okhit007** [comment] 2016-05-03 06:26
I still ger error with using android gradle plugin 2.10 and spoon-runner 1.5.2

**Comment by okhit007** [comment] 2016-05-03 06:26
I still get error with using android gradle plugin 2.10 and spoon-runner 1.5.2

**Comment by bagintz** [comment] 2016-06-28 13:12
I am getting this also, with gradle 2.10 and spoon 1.5.6, am I doing something wrong?

**Comment by kirillzh** [comment] 2016-06-29 20:20
@bagintz, should be fixed in [1.5.7](latest runner JAR).

**Comment by bagintz** [comment] 2016-06-30 01:21
Thanks guys!!

**Comment by sayoojvalsan-demandmedia** [comment] 2016-08-30 01:10
Im getting the same issue 
spoon runner/client 1.6.4
gradle spoon plugin 2.7.3
buildToolVersion 23.0.3
gradle 2.10


I notice the issue appears in Jenkins. Any ideas ?

**Comment by bwidulski-mdsol** [comment] 2022-07-19 20:41
Still have this issue, Spoon 2.0.0-SNAPSHOT, gradle 7.0.2
