### ISSUE TITLE
[Question] Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 111

### ISSUE THREAD

**Issue by mweerasi** [square/spoon#515] opened 2018-01-17 21:54 UTC
Initially I was getting this issue
`Exception in thread "main" java.lang.NullPointerException: SDK path not specified.
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226)
	at com.squareup.spoon.SpoonRunner$Builder.setAndroidSdk(SpoonRunner.java:344)
	at com.squareup.spoon.SpoonRunner.main(SpoonRunner.java:658)`
then I followed the instructions from a previous question to specify the sdk folder (I tried with --sdk first then just set the ANDROID_HOME variable but now I'm getting this issue
`Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 111
	at com.squareup.spoon.axmlparser.StringBlock.getShort(StringBlock.java:241)
	at com.squareup.spoon.axmlparser.StringBlock.getRaw(StringBlock.java:99)
	at com.squareup.spoon.axmlparser.StringBlock.read(StringBlock.java:66)
	at com.squareup.spoon.axmlparser.AXMLParser.doStart(AXMLParser.java:200)
	at com.squareup.spoon.axmlparser.AXMLParser.<init>(AXMLParser.java:48)
	at com.squareup.spoon.SpoonInstrumentationInfo.parseFromFile(SpoonInstrumentationInfo.java:57)
	at com.squareup.spoon.SpoonRunner.run(SpoonRunner.java:117)
	at com.squareup.spoon.SpoonRunner.main(SpoonRunner.java:695)`
How do I resolve this?

**Comment by JakeWharton** [comment] 2018-01-17 21:56
This is a dupe of #468 and fixed by #477 on master. You'll have to use 2.0.0-SNAPSHOT for now for the fix.

**Closed by JakeWharton** 2018-01-17 21:56 UTC
