### ISSUE TITLE
screenshot does not properly capture the screen

### ISSUE THREAD

**Issue by kpogz** [square/spoon#350] opened 2016-06-14 20:09 UTC
I am using spoon to take some screen shots on our new 'bottombar' in an android app during a UI test, and realized that it is not capturing our left most button, even though i see that it was on the screen during the espresso test.

This left button is being drawn, whereas the buttons that show up correctly are done with svgs. Any idea why Spoon would not capture whats actually visible?

Thanks so much!

**Comment by keven-pogrzeba** [comment] 2016-06-28 14:46
Is anyone able to help me investigate this? What needs to be done in order for the screenshot to be captured properly? Could anyone provide any resources?

**Comment by kwiky** [comment] 2016-07-05 13:23
I use FalconSpoon class from Falcon : https://github.com/jraska/Falcon#spoon-compat

**Comment by kpogz** [comment] 2016-07-27 18:16
I was able to get my screenshot to work by using screengrab(which i beleive is forked from spoon) and modifying the code a bit. it would be nice to see this go into spoon

**Comment by kpogz** [comment] 2016-07-27 18:28
Falcon worked great as well!

**Comment by gen0083** [comment] 2016-09-26 10:46
I met the same issue.
Project is here: https://github.com/gen0083/ViewDrawingTest

This project is a testing custom view draw as expected.
The view extends TextView and draw line around own.
Lines right side and bottom are drawn on real device expectedly.
But screenshot took by Spoon was not drawn.

**Comment by tir38** [comment] 2016-09-27 22:20
Screenshots are always helpful. What is Spoon capturing? What is Spoon supposed to be capturing?

Spoon doesn't do anything fancy to take screenshots. So drop some breakpoints in the source and see what dimensions your View is and compare it with what you *think* it should be. Specifically, put a breakpoint here: https://github.com/square/spoon/blob/master/spoon-client/src/main/java/com/squareup/spoon/Spoon.java#L94

**Comment by kpogz** [comment] 2016-09-29 19:50
check this out - notice the graphical issue on the 'progress bar' and the bottom menu bar is missing its button on the bottom left. never looks like this when running the app
![1475090461281_aftersignup2](https://cloud.githubusercontent.com/assets/15619911/18969714/4def5106-865c-11e6-90a5-857fe583d345.png)

**Comment by tir38** [comment] 2016-09-29 19:52
dumb question: is it only this screen that problems exist? or is Spoon always chopping that portion of the window?

**Comment by kpogz** [comment] 2016-09-29 19:55
yea, it vary by the screen. the other screens in this app are webviews and
dont have this problem. this developer told me these things were custom
drawn, which is maybe why spoon has trouble with it.

**Comment by tir38** [comment] 2016-10-04 14:36
What do you mean by custom drawn? Do you mean a custom view (i.e. your own subclass of View)?  If so then that shouldn't be a problem.

If you mean that it is rendered in a custom way then that could definitely be the source of your trouble. Find out if that view is creating its own `Window`. 

What happens if you add a "placeholder" view to your view hierarchy that "sit's behind" the missing part? Does Spoon correctly capture that?

**Comment by JakeWharton** [comment] 2017-04-26 02:48
Dupe of #4.

**Closed by JakeWharton** 2017-04-26 02:48 UTC
