### ISSUE TITLE
Spoon takes alot of time in copying screenshots and to generate report

### ISSUE THREAD

**Issue by harjitsinghfk** [square/spoon#341] opened 2016-05-13 18:05 UTC
Spoon is taking alot of time in copying the screenshots captured on all the devices and to generate report. Its like my test execution time is lesser than the spoon report generation time. Isn't the data being copied as soon as it is generated , I mean as soon as a screenshot is captured on a device , are you copying it to the local system immediately or are waiting till all the devices have finished running tests? An improvement on the report generation time would be really appreciated.

**Comment by JakeWharton** [comment] 2016-05-13 18:16
Copy happens after execution.

**Comment by JakeWharton** [comment] 2017-04-26 02:49
Dupe of #395

**Closed by JakeWharton** 2017-04-26 02:49 UTC
