### ISSUE TITLE
SpoonRunner hangs at execution end and no log file reports

### ISSUE THREAD

**Issue by RichardGuion** [square/spoon#251] opened 2015-03-25 01:41 UTC
I synced up to master and built spoon-runner jar locally (spoon-runner-1.1.9).

java -jar ../libs/spoon-runner-1.1.9-SNAPSHOT-jar-with-dependencies.jar --no-animations  --apk ./app/build/outputs/apk/evernote-allArch-evernote-instrumentation-unaligned.apk --test-apk ./app/build/outputs/apk/evernote-allArch-evernote-debug-test-unaligned.apk --class-name com.evernote.test.smoketests.EspressoTests --method-name testSignInSignOut_FreeUser --debug --output /Users/rguion/dev/reports/EspressoTests_testSignInSignOut_FreeUser

debug output:

2015-03-24 18:39:04 [SDR.run] About to actually run tests for [T065001D7F]
06:39:04 I/RemoteAndroidTest: Running am instrument -w -r  -e class com.evernote.test.smoketests.EspressoTests#testSignInSignOut_FreeUser com.evernote.test/android.support.test.runner.AndroidJUnitRunner on motorola-xt1053-T065001D7F
2015-03-24 18:39:05 [STRL.testRunStarted] testCount=1 runName=com.evernote.test
2015-03-24 18:39:05 [STRL.testStarted] test=com.evernote.test.smoketests.EspressoTests#testSignInSignOut_FreeUser
2015-03-24 18:39:44 [STRL.testEnded] test=com.evernote.test.smoketests.EspressoTests#testSignInSignOut_FreeUser
2015-03-24 18:39:44 [STRL.testRunEnded] elapsedTime=38685
06:39:44 I/XmlResultReporter: XML test result file generated at /Users/rguion/dev/android/./tests/reports/EspressoTests_testSignInSignOut_FreeUser/junit-reports/T065001D7F.xml. Total tests 1, passed 1,
2015-03-24 18:39:44 [SDR.run] About to grab screenshots and prepare output for [T065001D7F]
2015-03-24 18:39:44 [SDR.pullScreenshotsFromDevice] Internal path is /data/data/com.evernote/app_spoon-screenshots
2015-03-24 18:39:45 [SDR.pullScreenshotsFromDevice] External path is /storage/emulated/legacy/app_spoon-screenshots
2015-03-24 18:39:45 [SDR.pullScreenshotsFromDevice] Pulling screenshots from [T065001D7F]
2015-03-24 18:39:45 [SR.runTests] [T065001D7F] Execution done.

It just hangs. I have tried to debug it but cannot determine the problem.  No one else has seen this yet?

**Comment by edenman** [comment] 2015-03-25 01:54
Haven't seen that.  We changed how screenshots are stored/pulled in the latest version, might be a bug there.  

1) What version is your device?
2) How long did you wait?  I've seen slower adb pull times since we switched to storing screenshots on external storage.

**Comment by RichardGuion** [comment] 2015-03-25 02:17
Wait, I think this is my fault. I had made a workaround earlier on my screenshot location taking while I waited for you to fix spoon for Android L.  This is causing the problem.  Will close this ticket.

**Comment by tigerpenguin** [comment] 2015-03-25 20:35
I am seeing this same hanging issue using Spoon Runner 1.1.8 on JB 4.3 emulator. I am not using Spoon-Client and not taking any screen shots, just using Spoon Runner to execute an instrumentation test apk. Is it possible that it's hanging if there's no screenshots at all?

**Comment by tigerpenguin** [comment] 2015-03-25 21:29
Tried with screenshots, seems like it has nothing to do with it, still hanging for me after `Execution Done`. No logs either.

**Comment by tigerpenguin** [comment] 2015-03-25 22:38
Taking this discussion to https://github.com/square/spoon/issues/252

**Comment by edenman** [comment] 2015-03-26 05:13
Reopening as it seems like there's definitely an issue for some folks here.  Looks like this is probably the problematic commit (it was the only change in 1.1.6):
https://github.com/square/spoon/commit/cb3eb9573383c6ab543cdacd7ea4f5875b9766cc
cc @roman-mazur

**Comment by roman-mazur** [comment] 2015-03-26 07:15
I personally haven't faced with this yet. But will try analyze.

**Comment by roman-mazur** [comment] 2015-03-26 07:19
@RichardGuion do you run the tests on one device or multiple?

**Comment by roman-mazur** [comment] 2015-03-26 07:21
Looks like for one (from the log)...

**Comment by tigerpenguin** [comment] 2015-03-26 15:29
Some additional info about my setup, in case it helps:
```
Android Debug Bridge version 1.0.32
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)
OS X Yosemite 10.10.2
Android SDK Tools 24.1.2
Android SDK Platform-tools v22
Android SDK Build-tools v22
```
Running test on one emulator - JB 4.3 x86 image

**Comment by edenman** [comment] 2015-03-26 20:46
@tigerpenguin can you check out the branch in https://github.com/square/spoon/pull/254, `mvn install` it, and run your tests against `spoon-runner:1.1.9-SNAPSHOT`?  Added some more logging that may help track down where the issue is.

**Comment by tigerpenguin** [comment] 2015-03-26 21:06
Thanks @edenman, I pulled the latest master with your commit merged. The logs are working now, but it's still hanging for me.

Command I ran:
`java -jar spoon-runner-1.1.9-SNAPSHOT-jar-with-dependencies.jar --apk spoon-sample-app-1.1.9-SNAPSHOT.apk --test-apk spoon-sample-tests-1.1.9-SNAPSHOT.apk --debug --no-animations`

Last few lines of the output on terminal:
```
[STRL.testEnded] test=com.example.spoon.ordering.tests.MiscellaneousTest#testAnotherLongNameBecauseItIsHumorousAndTestingThingsLikeThisIsImportant
[STRL.testStarted] test=com.example.spoon.ordering.tests.OrderActivityTest#testMakeASandwich_ItTastesGood
[STRL.testEnded] test=com.example.spoon.ordering.tests.OrderActivityTest#testMakeASandwich_ItTastesGood
[STRL.testStarted] test=com.example.spoon.ordering.tests.OrderActivityTest#testMakeSomeSalad_ItIsHealthy
[STRL.testEnded] test=com.example.spoon.ordering.tests.OrderActivityTest#testMakeSomeSalad_ItIsHealthy
[STRL.testRunEnded] elapsedTime=35210
04:00:51 I/XmlResultReporter: XML test result file generated at /spoon/spoon-output/junit-reports/emulator-5554.xml. Total tests 9, failure 2, passed 7, 
[SDR.run] About to grab screenshots and prepare output for [emulator-5554]
[SDR.pullScreenshotsFromDevice] Internal path is /data/data/com.example.spoon.ordering/app_spoon-screenshots
[SDR.pullScreenshotsFromDevice] External path is /storage/sdcard/app_spoon-screenshots
[SDR.pullScreenshotsFromDevice] Pulling screenshots from external dir on [emulator-5554]
[SDR.pullScreenshotsFromDevice] Pulling screenshots from internal dir on [emulator-5554]
[SDR.pullScreenshotsFromDevice] Done pulling screenshots from [emulator-5554]
[SDR.run] Moving screenshots to the image folder on [emulator-5554]
[SDR.run] Generating animated gifs for [emulator-5554]
[SDR.run] Done running for [emulator-5554]
[SR.runTests] [emulator-5554] Execution done.

```

To clarify on the hanging, all the xml/html/logs are generated fine, the main method seems to exit, but the process just won't terminate.

**Comment by tigerpenguin** [comment] 2015-03-26 21:18
Looking over the commit https://github.com/square/spoon/commit/cb3eb9573383c6ab543cdacd7ea4f5875b9766cc, I tried something different this time. I didn't have any emulator running (or device connected) and executed spoon, and I noticed the same hanging behavior after the following output.
```
[SR.runTests] Executing instrumentation suite on 0 device(s).
[SR.runTests] Application: com.example.spoon.ordering from /spoon/spoon-sample-app-1.1.9-SNAPSHOT.apk
[SR.runTests] Instrumentation: com.example.spoon.ordering.tests from /spoon/spoon-sample-tests-1.1.9-SNAPSHOT.apk
```

When I reverted the commit and added the call to `AndroidDebugBridge.disconnectBridge()` and `AndroidDebugBridge.terminate()`, it properly exited.

**Comment by fahimahmed** [comment] 2015-04-06 12:51
Same result with 1.1.8 & 1.1.9. :(

![capture](https://cloud.githubusercontent.com/assets/5729534/7004486/c6fbc6bc-dc8d-11e4-9c3e-085db23d56bb.PNG)

**Comment by pokornyr** [comment] 2015-04-09 16:36
Hi all,

I have tested the version 1.1.9 for using the new argument -serial from our contributor to the project. I can confirm the fact that the SpoonRunner is hanging at the end of its execution since the version 1.1.6. I tried the version 1.1.5 in command line and I was prompted at the end. As the JAR files are part of our scripts, I cannot use them anymore. Is it possible to have this fixed in the next release?

**Comment by gnardini** [comment] 2015-04-20 13:31
Hi, I'm not sure if there's a fix for this but I couldn't find a solution. I'm having the same problem, only that logs do show up. All tests run correctly, screenshots and logs are formed but it just hangs when it's finished. These are the last few lines of the command line:

2015-04-20 10:21:55 [SDR.run] Moving screenshots to the image folder on [4790722b1b4acfe0]
2015-04-20 10:21:55 [SDR.run] Generating animated gifs for [4790722b1b4acfe0]
2015-04-20 10:22:11 [SDR.run] Done running for [4790722b1b4acfe0]
2015-04-20 10:22:11 [SR.runTests] [4790722b1b4acfe0] Execution done.

I'm executing the following:

java -jar ./spoon-runner-1.1.9-jar-with-dependencies.jar \
	--apk ./app/build/outputs/apk/app-stage-debug.apk \
	--test-apk ./app/build/outputs/apk/app-stage-debug-test-unaligned.apk \
	--sdk /home/gonzalonardini/Android/Sdk \
	--output ./tests \
	--debug

Any help would be greatly appreciated.

**Comment by pokornyr** [comment] 2015-04-20 15:16
The fix for this will be to rollback the commit done in version 1.1.6 and re-add the call to AndroidDebugBridge.disconnectBridge() and AndroidDebugBridge.terminate().

**Comment by pokornyr** [comment] 2015-04-22 15:50
Any updates if the fix will be available soon? We would like to use the request #250 submitted by Jesse "Add device command line option" with a release that does not hang at the end of execution else we would have to move on with an alternative solution.

**Comment by edenman** [comment] 2015-04-22 17:03
@roman-mazur have you had a chance to do any more investigation into this?  I'm tempted to roll back the disconnect/terminate changes until we get a better idea of why this happens for some folks.

**Comment by roman-mazur** [comment] 2015-04-22 20:18
My current guess is that I do not see some piece of code in Android Gradle plugin that actually does adb client termination... Because I do not see such a problem when it's run from Gradle.
I will post a question in adt-dev group asking about their task implementation details.

Meantime I believe you can feel free to roll back. Gradle plugin will continue to use the current version by default.

**Comment by roman-mazur** [comment] 2015-04-22 22:20
Posted a question
https://groups.google.com/forum/#!topic/adt-dev/1BgTs8Bs6_Q
I hope somebody will be not lazy enough to read it and answer :)

As I wrote in the question, I have an idea of how the proper usage of `AndroidDebugBridge`.
Basically, it should be getting `disconnect()` and `terminate()` invocations back to the code and leaving everything else as is. I hope such a variant should work both for the standalone tool and Gradle plugin. But I have not tried it yet in practice.
Not sure, whether I'll be able to do this by the end of the week though.

**Comment by edenman** [comment] 2015-04-23 01:20
@pokornyr I don't have time to do this today but if you want to submit a PR that rolls back the disconnect changes I'll merge and release tomorrow.

**Comment by pokornyr** [comment] 2015-04-23 16:27
I do not have the environment setup on my computer for generating the jar files and Jesse is OOTO until next week. What I can do if you have time to build the JAR files and drop it somewhere where I can access it, I would be able to validate it. Else, I would need to wait Jesse's return.

**Comment by pokornyr** [comment] 2015-04-27 15:13
@roman-mazur thanks for rolling back the fix done in 1.1.6.
Waiting for the next official version, i I will verify if SpoonRunner exits properly.

**Comment by roman-mazur** [comment] 2015-04-27 16:18
@pokornyr I have not submitted a PR. I pushed that commit to my repo.
The issue is that if you call `terminate()` and then create a new bridge, the new bridge fails to work.
And this is what happens if you run spoon tests for different flavors with Gradle :(

Hence, I decided to make this `terminate()` call optional and opt it out when `SpoonRunner` is used by gradle plugin. I'm feeling gross and bad about this approach but it's the only working approach I can imagine for now.

But I have not done it yet. Will try to submit a PR tomorrow.

**Comment by pokornyr** [comment] 2015-04-27 16:33
@roman-mazur Thanks for this update. Adding this as an option for Gradle will, at least, works for all. I am personally using SpoonRunner in a Linux shell script and do not have to open a new bridge.

Thanks also for submitting a PR.

**Comment by pokornyr** [comment] 2015-04-29 14:41
any update?

**Comment by pokornyr** [comment] 2015-04-29 19:56
I saw some commits done today. Is there any chance for this issue to be addressed before a new release?

**Comment by daj** [comment] 2015-05-26 04:06
Any progress on this one @roman-mazur?

**Comment by jamespullar** [comment] 2015-06-09 16:09
The fix @tigerpenguin mentions worked well for me. However I only reverted the changed to SpoonRunner.java in https://github.com/square/spoon/commit/cb3eb9573383c6ab543cdacd7ea4f5875b9766cc and left the call to AndroidDebugBridge.initIfNeeded() as it's a bit more robust than calling init() directly.

**Comment by jpratik21** [comment] 2015-06-11 17:12
Can confirm that I am also seeing this on the latest release, 1.1.9.  Hangs at end of execution.

**Comment by RichardGuion** [comment] 2015-07-03 01:17
I am also encountering this once again!

**Comment by pokornyr** [comment] 2015-07-03 02:21
I tried for weeks to get this fix done. roman-mazur was preparing the fix including an argument for the bridge disconnection. He never committed his fix. I found a workaround for now but still would like to see this fix done.

**Closed** 2015-07-05 19:01 UTC
Labels: bug

**Comment by edenman** [comment] 2015-07-05 19:09
Just pushed 1.1.10 to maven central, which includes this fix.  Thanks for your patience, all!

**Comment by roman-mazur** [comment] 2015-07-05 19:32
And sorry for the delay.

**Comment by pokornyr** [comment] 2015-07-07 14:03
@roman-mazur : thank you. I tested it and it disconnects the bridge by default.

**Comment by RichardGuion** [comment] 2015-07-09 01:44
Yes, it works great for me, too. Thanks @roman-mazur !

**Comment by kirillzh** [comment] 2016-07-28 17:16
I'm seeing this issue in `1.6.1`
